name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout @v4
      - uses: actions/setup-python @v5
        with: { python-version: '3.11' }
      - run: pip install -U pip wheel
      - run: pip install -e .
      - run: pip install fastapi uvicorn typer pytest ruff
      - run: ruff check .
      - run: pytest -q

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform -chdir=infra/tf init
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

      - name: Terraform Plan
        run: terraform -chdir=infra/tf plan
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
